FUNCTION(ADD_GTEST_TEST TARGET)
  ADD_MUDLET_TEST(${TARGET} "gmock;gtest_main;pthread" ${ARGN})
ENDFUNCTION()

FUNCTION(ADD_QT5_TEST TARGET)
  ADD_MUDLET_TEST(${TARGET} "Qt5::Test" ${ARGN})
ENDFUNCTION()

FUNCTION(ADD_MUDLET_TEST TARGET TEST_LIBS)
    ADD_EXECUTABLE(${TARGET} ${ARGN})
    TARGET_LINK_LIBRARIES(${TARGET}
        ${TEST_LIBS}
        mudletCore
        ${MUDLET_EXTERNAL_LIBS})

    ADD_TEST(NAME ${TARGET} COMMAND $<TARGET_FILE:${TARGET}>)
ENDFUNCTION()
